### ISSUE TITLE
AltroUSB producer fails to build

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#73]
The AltroUSB producer fails to compile on Linux with GCC 4.7 with the following error:

```
/home/hperrey/src/eudaq/producers/altroUSB/include/AltroUSBProducer.hh:4:20: fatal error: ilcdaq.h: No such file or directory
```

Error on Windows 7 with MSVC12:

```
/.../eudaq/producers/altroUSB/include\AltroUSBProducer.hh(2): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\hperrey\Desktop\eudaq\build\producers\altroUSB\AltroUSBProducer.exe.vcxproj]
```
