### ISSUE TITLE
Compilation error in USBPixI4ConverterPlugin using Clang

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#113]
Dear all,

the compilation of the master branch of EUDAQ currently fails on the USBPixI4ConverterPlugin:
```
[ 44%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/USBPixI4ConverterPlugin.cc.o
In file included from /Users/hanno/src/eudaq.tmp/eudaq/main/lib/src/USBPixI4ConverterPlugin.cc:6:
/Users/hanno/src/eudaq.tmp/eudaq/./main/include/eudaq/ATLASFE4IInterpreter.hh:133:22: error: call to non-static member function without an
      object argument
                enum{ shiftValue = getShift()};
                                   ^~~~~~~~
1 error generated.
```

This is on OSX 10.9.5, Clang 6.0 (LLVM 3.5svn), CMake 2.8.12.2 after a fresh clone of the repository and a simple ```cd build && cmake .. && make```.

**Comment by simonspa** [comment]
Compiles fine on Ubuntu 14.10 64bit, gcc 4.9.1, CMake 2.8.12.2.

**Comment by rubinsky** [comment]
should it compile with CLang at all?

**Comment by hperrey** [comment]
In my humble opinion: Yes, absolutely. First of all, it did before and made it a lot easier to use EUDAQ on OSX. And second of all, if one C++ compiler complains, it might only be only a matter of the next gcc version to come around before it fails there too.
I also do not believe it to be a good idea to write C++ code suited only for one compiler. And in fact, many projects use Clang as default by now, so it's not a niche compiler either.

**Comment by tbisanz** [comment]
I agree with Hanno, unfortunately I don't have CLANG installed, I guess simply adding "this->" doesn't fix it, right?

**Comment by simonspa** [comment]
Fixed in a259ff4aad2ca189d4da7019c152deba78659c0f
