### ISSUE TITLE
Compilation error in EventSynchronisationBase.cc using Clang (branch v2.0-dev)

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#114]
Dear all,

the compilation of the v2.0-dev branch of EUDAQ currently fails on EventSynchronisationBase.cc:
```
[ 11%] Building CXX object main/lib/CMakeFiles/EUDAQ.dir/src/EventSynchronisationBase.cc.o
/Users/hanno/src/eudaq.tmp/eudaq/main/lib/src/EventSynchronisationBase.cc:232:21: error: non-const lvalue reference to type
      'shared_ptr<[...]>' cannot bind to a temporary of type 'shared_ptr<[...]>'
      det->AddEvent(std::shared_ptr<Event>(nullptr));
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/hanno/src/eudaq.tmp/eudaq/./main/include/eudaq/DetectorEvent.hh:24:43: note: passing argument to parameter 'evt' here
    void AddEvent(std::shared_ptr<Event>& evt);
                                          ^
1 error generated.
```
This is on OSX 10.9.5, Clang 6.0 (LLVM 3.5svn), CMake 2.8.12.2 after a fresh clone of the repository, a checkout of the ```v2.0-dev``` branch and a simple ```cd build && cmake .. && make```.

**Comment by dreyling** [comment]
It is working/compiling for Ubuntu 14.04, gcc 4.8.4, CMake 2.8.12.2, a fresh clone of the repository and a checkout of the v2.0-dev branch.

**Comment by arummler** [comment]
Branch v2.0-dev has been retired and replaced by master. The current master branch builds on the travis CI with clang 6.0, darwin 13.4.0, cmake 3.4.3. As this report is otherwise more than a year old I am closing it.
