### ISSUE TITLE
miniTLU executables fail to build

### ISSUE THREAD

**Issue by hperrey** [eudaq/eudaq#75]
The ```miniTLUControl.exe``` executable fails to compile on Linux GCC 4.7 due to missing includes:
```
/home/hperrey/src/eudaq/producers/miniTLU/include/tlu/miniTLUController.hh:13:25: fatal error: uhal/uhal.hpp: No such file or directory
```

**Comment by Eyiliu** [comment]
minitluproducer is upated
